### ISSUE TITLE
Trakt Progress

### ISSUE THREAD

**Issue by derrgoo** [host505/plugin.video.theoath#20]
Sorry, not sure where to write this. I may have made duplicates. 

I was wondering how to get fanart to show on my widget when I use trakt progress for tv series? Currently there are only regular pictures no fanart. 

Thanks

**Comment by host505** [comment]
I'm aware of this.
Add-on since recently uses TMDb api for tv shows metadata. The problem is that tmdb episodes api endpoint doesn't offer other types of images than thumbs. So most episodes lists (Trakt progress/episodes/history/continue watching) only have thumbs.
Sure I could make calls to other api endpoints to grab them, but I don't really want to.
I'm still thinking of how to proceed regarding this issue.

**Comment by derrgoo** [comment]
Thanks. Thought it was just me not being able to figure out. Glad you thinking about this and look forward to a remedy. Thanks!

**Comment by host505** [comment]
With latest version (4.00.15) there should be fanart and other art types on episodes lists.

Though, I wish people Not to use this add-on for widgets, at least not for episodes lists widgets.
There's no proper cacheing of episodes lists metadata. Exodus (which is the roots of this add-on) wasn't really designed with that usecase in mind.

**Comment by derrgoo** [comment]
I got the update but wasn’t able to see any fanart. I pulled from episode s.

**Comment by host505** [comment]
It works on all my systems (3 different platforms) and from feedback I got.
If you need further assistance I'm gonna need more info and some logs.
