### ISSUE TITLE
Update Library not working as expected.

### ISSUE THREAD

**Issue by TNTPro** [host505/plugin.video.theoath#29]
Hi,
  There seems to be a problem with the library part of the addon.  I have added 100 series to my library using theoath.  The folders and STRM files get created fine.  Later, when theoath does an "update library", not all the series get the new STRM files.
  I'm assuming the "library.1.db" file in the "addon_data\plugin.video.theoath" folder is the library that theoath uses.  With this in mind, I opened the "library.1.db" file in DB Browser and noticed, that there was only 58 tvshows in the database and that the series that were not updating, were not in this file. ("The Grand Tour" and "Roswell, New Mexico" were 2 of these).  Whether my assumptions are correct or not, the problem that not all series are getting new episodes, is still occurring.
If you need any more info, I'll be glad to provide what I can.
[library.1 and series list.zip](https://github.com/host505/plugin.video.theoath/files/6911822/library.1.and.series.list.zip)

**Comment by host505** [comment]
No that .db file is not what you think it is. What's listed there is the last season of ended series.
For the not added episodes, check their status on tmdb (if they have updated release date).

**Comment by TNTPro** [comment]
I have already checked on TMDB and the new episodes are there and have been for at least a few days.  No updated release dates that I can see.  I have watched some of the eps in question.  If I "add" the series again, the eps appear, but not if I use "update library".

**Comment by host505** [comment]
Ok I'll have a closer look.

**Comment by host505** [comment]
Couldn't reproduce your issue. My shows update, and I even added The Grand Tour you mentioned, removed the latest episode, cleaned library, updated library through the addon, and the episode came back.
Gonna need logs if you want further assistance, enable add-on logging, reproduce the issue and send me the theoath.log.

**Comment by TNTPro** [comment]
I'm using Ember to manage my artwork & nfos.  Would that cause a problem?

**Comment by host505** [comment]
All the add-on does is to generate the folder structure, .strm, .nfo files and trigger Kodi's library update action (if enabled).
Are new episodes .strm files generated by the add-on?
If not, I'm gonna need that log file.

**Comment by TNTPro** [comment]
Here's the log file you wanted.
[theoath.zip](https://github.com/host505/plugin.video.theoath/files/6913417/theoath.zip)

**Comment by host505** [comment]
Is your device's system time working?

**Comment by TNTPro** [comment]
as far as I know. The clock always seems to be correct.

**Comment by TNTPro** [comment]
Here's a debug log from another device (desktop Ubuntu 18)
[theoath.zip](https://github.com/host505/plugin.video.theoath/files/6913596/theoath.zip)

**Comment by host505** [comment]
The only unusual error from these logs is this:
```
[2021-08-01 23:51:27] [ TheOath DEBUG ]: lib_ep_upd5: Traceback (most recent call last):
  File "/home/tec/.kodi/addons/plugin.video.theoath/resources/lib/modules/libtools.py", line 572, in update
    if (premiered != '0' and int(re.sub('[^0-9]', '', str(premiered))) > int(self.date)) or (premiered == '0' and not self.include_unknown):
ValueError: invalid literal for int() with base 10: ''
```
which indicates something's wrong with system's date fetching.
Since I can't reproduce the error, you're gonna have to do some things if you want this investigated.
Replace .kodi\addons\plugin.video.theoath\resources\lib\modules\libtools.py with the attached one (remove the .txt extension), reproduce the issue and send me the log.
Ps no log zips please, you can go to Tools/Log Functions/Upload Log and post the link you'll be given.
[libtools.py.txt](https://github.com/host505/plugin.video.theoath/files/6915883/libtools.py.txt)

**Comment by TNTPro** [comment]
Here's the log with the new libtools.py
https://paste.kodi.tv/usobiqiqam

**Comment by host505** [comment]
Nah that error was from episodes not yet having a release date - expected.
There's actually nothing indicating that something went wrong. Not sure what your issue is, nor have I gotten any more issue reports about this, and it's working for me as well.
I suppose something on your install combination - do you have any other add-ons putting stuff to your library?

**Comment by TNTPro** [comment]
No  I don't have any other addons adding stuff to the library.  I'll do some more tests on a vanilla install, on the same devices, to see if it's any different.  But that probably wont be for 2-3 days, as I got long work shifts.

**Comment by TNTPro** [comment]
Sorry for the delay, but I've finally got around to some testing.
I tried a vanilla setup this morning and it did indeed update the episodes OK.  I then deleted some of the new episodes, so I could start diagnosing what the conflict in my setup was.  To get a base log with my original setup, I ran the Update library in theoath and it to my suprise the new episodes appeared again.
So it would seem an update (or maybe some magic) has sorted this problem.  Thanks, that's great.
One thing I noticed while doing all this, was that, theoath is over writing my tvshow.nfo files, but maybe I should open a separate ticket for that.

**Comment by host505** [comment]
From what I gathered you point theoath's library folders to your local media sources folders. Don't do that. Keep them separated. Add-on will see what you already have in your library and will skip those. There's a setting for that, to avoid duplicating content - default is on.
If you point it on your local library folders, it will overwrite your nfos. Add-on generates a parsing nfo.
https://kodi.wiki/view/NFO_files/Parsing

**Comment by TNTPro** [comment]
I keep my local media (tv shows, movies, etc.) separate from theoaths folders, but I use Ember to generate local artwork and NFOs, for theoath.
How difficult would it be to get theoath to honor the combination nfo?
[https://kodi.wiki/view/NFO_files/Combination](url)
As it seems to be a great solution.

**Comment by host505** [comment]
Not sure how a combination nfo would be of use on the way we add stuff. That's to bypass some info from metadata scrapers and use your own, custom meta.
So I guess your problem was the use of external metadata scraper - something that was never taken into account for the add-on's library integration function.
Best I can do is to consider making the creation of nfo in general optional.
