### ISSUE TITLE
Download Movies

### ISSUE THREAD

**Issue by Mr-Barillas** [host505/plugin.video.theoath#30]
Guys, question, how can i see the status of a download in the oath, or resume it after kodi is re-opened? 
the plugin continues downloading but is not copying the file anymore. 

that only happens if you exit the codi app an enter again, even if you do it by mistake. 

im using a smb network connection.

**Comment by host505** [comment]
Doesn't the notification every 10% appear on you?
That's the only way to see the status.
As for resuming after restart, not supported - no idea if it works or not.
Downloading is just a supplementary feature, it's very basic. I actually haven't touched it much since the og exodus, only done some compatibility fixes etc, and don't intend to.
