### ISSUE TITLE
Glodls torrent scraper 

### ISSUE THREAD

**Issue by Tinuz97** [host505/plugin.video.theoath#5]
They have changed the website (it was down for a few days), looks like the changes has broken the scraper also (no results), just fyi.

Greetings, and thx for the great addon (like the new multi line! Much better to read the results in the aeon nox silvo mod skin)

**Comment by host505** [comment]
Last time I checked their search engine was under maintenance, now it's the whole site.
I don't like the message on their maintenance page, they might implement some sort of captcha. We'll see.
Thanks

**Comment by Tinuz97** [comment]
Yeah, under maintenance again, but thx for checking 👍

**Comment by jewbmx** [comment]
1 day 9 hours left on that slow wait lol

**Comment by Tinuz97** [comment]
Yesterday it was up for a while, and the 'scraper' did work fine.
Kickass is broken I guess (  new website?)

**Comment by jewbmx** [comment]
Wouldnt know lol i moved it to a temp folder and just check in a browser every day to see if its ready yet, 90% chance of a rewrite needed since its down this long, unless they are just 'implementing' another db in.

Here ya go hope it copys over nicely for ya. Some are trickyISH as they are a proxy style.

self.domains = ['kickasshydra.net', 'kickasstrusty.com', 'kickassindia.com',
            'kickassmovies.net', 'torrentskickass.org', 'kickasstorrents.li', 'kkat.net',
            'kickassdb.com', 'kickassaustralia.com', 'kickasspk.com', 'kkickass.com',
            'kathydra.com', 'kickasst.org', 'kickasstorrents.id', 'kickasst.net', 'thekat.cc',
            'thekat.ch', 'kickasstorrents.bz', 'kickass-kat.com', 'kickass-usa.com'
        ]
