### ISSUE TITLE
Number of unwatched episodes count not present in TheOath?

### ISSUE THREAD

**Issue by Madddcow** [host505/plugin.video.theoath#50]
Hi.  I've noticed that, unlike other plugins like Seren and Venom, TheOath doesn't appear to include the unwatched episode count in numbers within TV show lists; instead there's just an unchecked box for each TV show listing if there are unwatched episodes (as opposed to shows where all episodes have been watched and this box is checked with a tick).

Am I missing a setting to turn on the unwatched episode count or am I right that TheOath doesn't have this feature?  If it _doesn't_ have this feature, is it possible to add it?

Cheers

**Comment by host505** [comment]
It's just a feature that is not there.
If you're talking about trakt indicators, seren and venom have developed some advanced cacheing methods that help with this, otherwise it would take extra calls to trakt with each list loading, resulting in longer loading times etc
I don't see it happening in theoath for the foreseeable future.
