### ISSUE TITLE
Orion integration

### ISSUE THREAD

**Issue by jjred1977** [host505/plugin.video.theoath#7]
I've been working with Orions devs (I test their filters) and we wanted to know if you would be able to or would consider adding the ability in your add on to make Orion results a different color like torrents and debrid results can be in different add ons? After integration with Orion it is hard to see which result are Orions in the scrape list. Gaia is best at showing Orions result details and Seren tries but is still not completely there yet. The dual line in scrape results helps but having to sit on a result for it to scroll Orion information is a pain. 

Anyway, Im happy with the work you've done already.

**Comment by host505** [comment]
TBH: I wouldn't like more colors on the source list. If you've noticed, unlike most similar add-ons, I don't even have extra color options for torrents (they get the debrid/premium coloring).
Creating extra colors for orion sources would complicate things, because I'd need to create 2 extra color options, 1 for premium (debrid resolved) Orion links and 1 for normal Orion links.
I came up with a different approach: optional different color just for the 'ORION' source label. I'll upload a photo to show and see what's you think.

The other issue you mentioned (about the extra info appearance), not much that I can do. Unlike Seren/Gaia that use custom dialogs for the sources, the Exodus base uses kodi's built-in windows/dialogs for that, and you can't customize them more afaik.
Creating custom dialogs is something I don't have any idea about.

**Comment by jjred1977** [comment]
Ok I understand. I appreciate you doing that much.

**Comment by host505** [comment]
So what'd you think about my approach (pic above), should I implement it or wouldn't make much of a difference?

**Comment by jjred1977** [comment]
It makes it much easier to see Orion results and like you said you don't have to mess with a lot of other things.  If Orion only gives one result it would be way easier to find the way you have it in the screenshot than looking for wording.  Colors just "pop" and stand out from the rest of the text.

**Comment by host505** [comment]
https://github.com/host505/plugin.video.theoath/commit/31e225248bcab147607f31e9d3b711b36bb71c94

**Comment by jjred1977** [comment]
thanks for adding the option.
